Fix Docker Hub login with password

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -34,12 +34,20 @@ jobs:
 
     - name: Add EC2 host to known_hosts 🌐
       run: |
-        # Verificar si el directorio ~/.ssh ya existe, si no, crearlo
+        echo "Verificando si ~/.ssh existe y creándolo..."
         mkdir -p ~/.ssh
         chmod 700 ~/.ssh
-        # Añadir la clave del host EC2
-        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
+        echo "Añadiendo la clave del host EC2..."
+        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts || echo "Error: No se pudo añadir la clave del host EC2"
         chmod 644 ~/.ssh/known_hosts
+        echo "La clave del host EC2 se añadió correctamente."
+
+    - name: Test SSH connection to EC2 🔒
+      run: |
+        echo "Probando la conexión SSH a EC2..."
+        ssh -T -o StrictHostKeyChecking=no -i private_key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
+          echo "Conexión SSH exitosa a EC2."
+        EOF
 
     - name: Deploy to EC2 (Optional) 🌐
       env:
@@ -50,7 +58,10 @@ jobs:
         # Guardar la clave privada en un archivo temporal y establecer permisos
         echo "$PRIVATE_KEY" | tr -d '\r' > private_key.pem  # Quitar saltos de línea adicionales
         chmod 600 private_key.pem
+        echo "La clave privada SSH se almacenó correctamente."
+
         # Asegurarse de que la clave se maneje correctamente para la conexión SSH
+        echo "Conectando a EC2 para desplegar..."
         ssh -T -o StrictHostKeyChecking=no -i private_key.pem $USER@$HOST << 'EOF'
           sudo docker pull erickuce/projectawsstore-deletecustomer:latest
           sudo docker run -d -p 8084:8084 erickuce/projectawsstore-deletecustomer:latest
